# Evaluation of pair trading

In [34]:
import importlib
import Pairs_trading


import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

importlib.reload(Pairs_trading)

In [37]:
def evaluate(String_array):

    rows = []

    for left, right in String_array:
        revenue_analysis, trades_analysis, revenue_trading, trades_trading = Pairs_trading.main(left, right)
        rows.append((left, right, revenue_analysis, revenue_trading))

        revenue_analysis, trades_analysis, revenue_trading, trades_trading = Pairs_trading.main( right, left)
        rows.append((right, left, revenue_analysis, revenue_trading))



    df = pd.DataFrame(
        rows,
        columns=["left", "right", "revenue analysis", "revenue test"]
    )

    return(df)

   left right  revenue analysis  revenue test
0  LRCX  AMAT          7.754404    -10.841359
1  AMAT  LRCX         14.491951     21.919481
2  AVGO  NVDA         36.834150      3.962074
3  NVDA  AVGO          7.535393     18.497228

# Pairs Trading NVDA
Here we perform the pairs trading with NVIDA since it had the highest Correlation

In [46]:
#[['NVDA','AVGO'],['NVDA','MPWR'],['LRCX','NVDA'],['KLAC','NVDA'],['MRVL','NVDA']]

results_NVDA=evaluate([['NVDA','AVGO'],['NVDA','MPWR'],['LRCX','NVDA'],['KLAC','NVDA'],['MRVL','NVDA']])
display(results_NVDA)

print('average revenue analysis: ',float(results_NVDA['revenue analysis'].sum())/10)
print('average revenue test: ',float(results_NVDA['revenue test'].sum())/10)

   left right  revenue analysis  revenue test
0  NVDA  AVGO          7.535393     18.497228
1  AVGO  NVDA         36.834150      3.962074
2  NVDA  MPWR         -4.818985     11.105688
3  MPWR  NVDA          0.908329      9.335317
4  LRCX  NVDA         15.987907    -12.835972
5  NVDA  LRCX        -13.293923     14.323108
6  KLAC  NVDA          5.138704      2.241198
7  NVDA  KLAC         -4.736231      6.441857
8  MRVL  NVDA         23.878545     13.701380
9  NVDA  MRVL          8.392130    -10.856169

average revenue analysis:  7.582601892618098
average revenue test:  5.591570905357978

# Pairs trading highest correlation

In [47]:

#[['LRCX','KLAC'],['LRCX','AMAT'],['KLAC','AMAT'],['MCHP','NXPI'],['MCHP','ADI']]

results_corr=evaluate([['LRCX','KLAC'],['LRCX','AMAT'],['KLAC','AMAT'],['MCHP','NXPI'],['MCHP','ADI']])
display(results_corr)

print('average revenue analysis: ',float(results_corr['revenue analysis'].sum())/10)
print('average revenue test: ',float(results_corr['revenue test'].sum())/10)

   left right  revenue analysis  revenue test
0  LRCX  KLAC          3.741435     -1.555622
1  KLAC  LRCX          3.925133      5.070053
2  LRCX  AMAT          7.754404    -10.841359
3  AMAT  LRCX         14.491951     21.919481
4  KLAC  AMAT         -0.018394      1.680261
5  AMAT  KLAC          6.850304      4.538338
6  MCHP  NXPI         -9.656370     -0.820619
7  NXPI  MCHP         -0.034769      0.885703
8  MCHP   ADI         -7.865858      2.252048
9   ADI  MCHP         -2.823143     -1.050800

average revenue analysis:  1.6364694004644313
average revenue test:  2.207748307542024