# Evaluation of pair trading

In [1]:
import importlib
import S3_Pairs_trading

import pandas as pd

S3_Pairs_trading = importlib.reload(S3_Pairs_trading)

In [2]:
def evaluate(String_array):
    rows = []
    for left, right in String_array:
        revenue_analysis, trades_analysis, revenue_test, trades_test = S3_Pairs_trading.main(left, right)
        rows.append((left, right, revenue_analysis, revenue_test))

        revenue_analysis, trades_analysis, revenue_test, trades_test = S3_Pairs_trading.main( right, left)
        rows.append((right, left, revenue_analysis, revenue_test))
    df = pd.DataFrame(
        rows,
        columns=["left", "right", "revenue analysis", "revenue test"]
    )
    return(df)

# Pairs trading suggested by Cointegration in the Dickey-Fuller test
Here we perform the pairs trading with the highest cointegration pairs

In [3]:
results_coint=evaluate([['MU','MPWR'], ['MU','KLAC'],['QRVO','MCHP'],['TXN','ADI'],['TER','TXN']])
display(results_coint)

print('average revenue analysis: ',float(results_coint['revenue analysis'].mean()))
print('average revenue test for all: ',float(results_coint['revenue test'].mean()))
print('average revenue test with revenue in analysis: ',float(results_coint[results_coint['revenue analysis']>0]['revenue test'].mean()))
corr=results_coint.loc[:,['revenue analysis','revenue test']].corr()
print('Correlation analysis & test:',corr.loc['revenue analysis','revenue test'])

   left right  revenue analysis  revenue test
0    MU  MPWR         -8.901715    -52.137823
1  MPWR    MU         -8.147103    -53.953380
2    MU  KLAC         69.776307   -105.148606
3  KLAC    MU         76.908570    -97.739183
4  QRVO  MCHP         76.029341     13.480360
5  MCHP  QRVO         70.117333      5.335295
6   TXN   ADI         50.150091      3.331245
7   ADI   TXN         58.654553      1.692581
8   TER   TXN         50.157928   -164.154920
9   TXN   TER         52.654914   -208.239792

average revenue analysis:  48.74002181040311
average revenue test for all:  -65.75342224784515
average revenue test with revenue in analysis:  -68.93037751430575
Correlation analysis & test: 0.025571834837375768

# Pairs trading highest correlation
Here we perform the pairs trading with the highest correlated stocks excluding NVIDA

In [4]:
results_corr=evaluate([['LRCX','KLAC'],['LRCX','AMAT'],['KLAC','AMAT'],['MCHP','NXPI'],['MCHP','ADI']])
display(results_corr)


print('average revenue analysis: ',float(results_corr['revenue analysis'].mean()))
print('average revenue test for all: ',float(results_corr['revenue test'].mean()))
print('average revenue test with revenue in analysis: ',float(results_corr[results_corr['revenue analysis']>0]['revenue test'].mean()))
corr=results_corr.loc[:,['revenue analysis','revenue test']].corr()
print('Correlation analysis & test:',corr.loc['revenue analysis','revenue test'])

   left right  revenue analysis  revenue test
0  LRCX  KLAC         11.900918    -24.158375
1  KLAC  LRCX         11.496339    -22.003840
2  LRCX  AMAT          2.834272    -43.706914
3  AMAT  LRCX          4.350603    -46.334777
4  KLAC  AMAT         18.529878    -38.247055
5  AMAT  KLAC         22.044686    -32.361854
6  MCHP  NXPI         -6.397028      3.118894
7  NXPI  MCHP          6.176916      4.911153
8  MCHP   ADI        -17.349651    -19.116351
9   ADI  MCHP        -25.032900     -9.116632

average revenue analysis:  2.855403203482541
average revenue test for all:  -22.701575137565143
average revenue test with revenue in analysis:  -28.843094546129358
Correlation analysis & test: -0.4333517215949134

# Pairs Trading NVDA
Here we perform the pairs trading with NVIDA and the highest correlated stocks

In [5]:
results_NVDA=evaluate([['NVDA','AVGO'],['NVDA','MPWR'],['LRCX','NVDA'],['KLAC','NVDA'],['MRVL','NVDA']])
display(results_NVDA)


print('average revenue analysis: ',float(results_NVDA['revenue analysis'].mean()))
print('average revenue test for all: ',float(results_NVDA['revenue test'].mean()))
print('average revenue test with revenue in analysis: ',float(results_NVDA[results_NVDA['revenue analysis']>0]['revenue test'].mean()))
corr=results_NVDA.loc[:,['revenue analysis','revenue test']].corr()
print('Correlation analysis & test:',corr.loc['revenue analysis','revenue test'])

   left right  revenue analysis  revenue test
0  NVDA  AVGO         27.318277     31.273542
1  AVGO  NVDA         22.557828     32.615199
2  NVDA  MPWR        -33.942894     78.133530
3  MPWR  NVDA        -87.520049     83.370405
4  LRCX  NVDA       -104.858619    -35.878785
5  NVDA  LRCX        -23.389587    -48.758585
6  KLAC  NVDA       -115.566702     11.571775
7  NVDA  KLAC         34.993020     -8.554150
8  MRVL  NVDA        -38.655456     32.825511
9  NVDA  MRVL         25.293428     44.598387

average revenue analysis:  -29.377075429242932
average revenue test for all:  22.119682883987565
average revenue test with revenue in analysis:  24.9832447039968
Correlation analysis & test: 0.05605441888986473